/**
 * Generates MOC (Map of Content) notes in the vault from Knowledge Mesh data:
 *  - "QLTY Platform MOC" — services grouped by bounded context (graph BELONGS_TO)
 *  - "Commissions MOC"   — solution-design docs grouped by stage (folder)
 *
 * Regenerate any time with: pnpm moc
 * The notes are marked `generated: knowledge-mesh-moc`; manual edits will be overwritten.
 */
import fs from "node:fs";
import path from "node:path";
import { config, pool } from "../packages/shared/src/index.ts";

function header(title: string): string {
  return `---
generated: knowledge-mesh-moc
tags: [moc]
---

# ${title}

> Generated by Knowledge Mesh (\`pnpm moc\`) — do not edit by hand.

`;
}

async function qltyMoc(): Promise<string> {
  const { rows } = await pool.query(`
    SELECT bc.name AS context, s.name AS service, d.path,
           left(coalesce(s.metadata->>'summary', split_part(d.content, 'purpose:', 2)), 140) AS hint
    FROM relations r
    JOIN entities s ON s.id = r.source_entity_id
    JOIN entities bc ON bc.id = r.target_entity_id
    LEFT JOIN documents d ON d.id = s.document_id
    WHERE r.relation_type = 'BELONGS_TO' AND bc.type = 'BoundedContext'
      AND d.path LIKE 'technologies/qlty/%'
    ORDER BY bc.name, s.name`);

  let out = header("QLTY Platform MOC");
  out += `${rows.length} services across bounded contexts. Ask Knowledge Mesh for details: \`knowledge_impact(<service>)\`, \`knowledge_get(<path>)\`.\n`;

  let context = "";
  for (const row of rows) {
    if (row.context !== context) {
      context = row.context;
      out += `\n## ${context}\n\n`;
    }
    const rel = path.relative("technologies/qlty", row.path);
    const name = row.service.includes("/") ? row.service.split("/").pop() : row.service;
    out += `- [${name}](${rel.split(path.sep).join("/")})\n`;
  }
  return out;
}

async function commissionsMoc(): Promise<string> {
  const base = "projects/solution_designs/commissions";
  const { rows } = await pool.query(
    `SELECT path, title FROM documents
     WHERE path LIKE $1 AND path NOT LIKE '%MOC%'
     ORDER BY path`,
    [`${base}/%`]
  );

  const byStage = new Map<string, { path: string; title: string }[]>();
  for (const row of rows) {
    const rel = row.path.slice(base.length + 1);
    const stage = rel.includes("/") ? rel.split("/")[0] : "(root)";
    if (!byStage.has(stage)) byStage.set(stage, []);
    byStage.get(stage)!.push(row);
  }

  let out = header("Commissions MOC");
  out += `${rows.length} solution-design documents by stage.\n`;
  for (const [stage, docs] of [...byStage.entries()].sort()) {
    out += `\n## ${stage}\n\n`;
    for (const doc of docs) {
      const rel = doc.path.slice(base.length + 1);
      out += `- [${doc.title}](${rel.split(path.sep).join("/")})\n`;
    }
  }
  return out;
}

const targets: [string, string][] = [
  [path.join(config.vaultPath, "technologies/qlty/QLTY Platform MOC.md"), await qltyMoc()],
  [path.join(config.vaultPath, "projects/solution_designs/commissions/Commissions MOC.md"), await commissionsMoc()],
];

for (const [file, content] of targets) {
  fs.writeFileSync(file, content, "utf8");
  console.log(`wrote ${path.relative(config.vaultPath, file)} (${content.length} chars)`);
}
await pool.end();
